<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions 
xmlns:extns="http://www.example.org/schema/1593562316251" 
xmlns:tns="http://www.example.org/wsdl/SOAPDataInitial" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
name="SOAPData" targetNamespace="http://www.example.org/wsdl/SOAPDataInitial">

  <wsdl:import namespace="http://www.example.org/schema/1593562316251"/>
  <wsdl:message name="inputDataRequest">
    <wsdl:part element="extns:inputDataRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="inputDataResponse">
    <wsdl:part element="extns:inputDataResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="SOAPData">
    <wsdl:operation name="inputData">
      <wsdl:input message="tns:inputDataRequest" name="inputDataInput"/>
      <wsdl:output message="tns:inputDataResponse" name="inputDataOutput"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
